const fs = require("fs");
const path = require("path");
const { PNG } = require("pngjs");

const IN_W = Number(process.env.IN_W || 64);
const IN_H = Number(process.env.IN_H || 48);
const OUT_W = Number(process.env.OUT_W || 32);
const OUT_H = Number(process.env.OUT_H || 24);
const FPS = Number(process.env.FPS || 10);
const TITLE = process.env.TITLE || "BADAPPLE";
const DIR = process.env.FRAMES_DIR || "./frames";
const OUT = process.env.OUT || "./frames-ba4.js";

function bitAt(png, x, y) {
  const i = (y * png.width + x) * 4;
  const r = png.data[i], g = png.data[i + 1], b = png.data[i + 2];
  return ((r + g + b) / 3) > 128 ? 1 : 0;
}

function encodeRleBase36(bits) {
  let start = bits[0];
  let last = bits[0];
  let count = 1;
  const runs = [];

  for (let i = 1; i < bits.length; i++) {
    if (bits[i] === last) {
      count++;
    } else {
      runs.push(count.toString(36));
      last = bits[i];
      count = 1;
    }
  }
  runs.push(count.toString(36));
  return { start, rle: runs.join(".") };
}

const files = fs.readdirSync(DIR)
  .filter(f => /\.png$/i.test(f))
  .sort();

if (!files.length) throw new Error(`No PNG files found in ${DIR}`);

const frames = [];
let maxLen = 0;
let maxFrame = 0;

for (const file of files) {
  const png = PNG.sync.read(fs.readFileSync(path.join(DIR, file)));
  if (png.width !== IN_W || png.height !== IN_H) {
    throw new Error(`${file}: expected ${IN_W}x${IN_H}, got ${png.width}x${png.height}`);
  }

  const bits = [];
  for (let y = 0; y < OUT_H; y++) {
    for (let x = 0; x < OUT_W; x++) {
      const sx = Math.min(IN_W - 1, Math.floor((x + 0.5) * IN_W / OUT_W));
      const sy = Math.min(IN_H - 1, Math.floor((y + 0.5) * IN_H / OUT_H));
      bits.push(bitAt(png, sx, sy));
    }
  }

  const enc = encodeRleBase36(bits);
  frames.push([enc.start, enc.rle]);

  const len = String(enc.start).length + enc.rle.length + 8;
  if (len > maxLen) {
    maxLen = len;
    maxFrame = frames.length - 1;
  }
}

const js = `// Auto-generated by encode-ba4.js
const BA4_META = ${JSON.stringify({
  protocol: "BA4",
  width: OUT_W,
  height: OUT_H,
  fps: FPS,
  title: TITLE,
  frames: frames.length
})};
const BA4_FRAMES = ${JSON.stringify(frames)};
`;

fs.writeFileSync(OUT, js, "utf8");
console.log(`BA4 encoded ${frames.length} frames -> ${OUT}`);
console.log(`meta: ${OUT_W}x${OUT_H} ${FPS}fps title=${TITLE}`);
console.log(`max encoded frame approx length=${maxLen} at frame=${maxFrame}`);
console.log(`meta packet: M|${OUT_W}|${OUT_H}|${FPS}|${TITLE}`);
console.log(`frame packet: F|frame|start|rle|fpsx10`);
